[pytest]
# Playwright settings
addopts = --browser chromium --browser-channel chrome --headed

# Test markers
markers =
    smoke: Quick functional tests
    regression: Full regression suite
    account: Tests related to specific user accounts
    negative: Negative test cases
    visual: Visual regression indicators

# Logging
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
